### ISSUE TITLE
AttributeError: module 'serial' has no attribute 'Serial'

### ISSUE THREAD

**Issue by OskarZyg** [drewarnett/pypicoboard#2]
Traceback (most recent call last):
  File "e:/Desktop/cv/main.py", line 2, in <module>
    pb = PicoBoard('COM1')    # or 'COM1' or '/dev/ttyS0', etc.
  File "C:\Users\oskil\AppData\Local\Programs\Python\Python38-32\lib\site-packages\picoboard.py", line 66, in __init__
    self._interface = serial.Serial(serial_port, 38400, timeout=0.1)
AttributeError: module 'serial' has no attribute 'Serial

My Modules:
aiohttp                3.6.2
APScheduler            3.6.3
async-timeout          3.0.1
attrs                  19.3.0
autoit                 0.1
certifi                2020.6.20
chardet                3.0.4
click                  7.1.2
comtypes               1.1.7
cycler                 0.10.0
discord.py             1.3.4
dnspython              1.15.0
dnspython3             1.15.0
Flask                  1.1.2
future                 0.18.2
idna                   2.10
iso8601                0.1.12
itsdangerous           1.1.0
Jinja2                 2.11.2
kiwisolver             1.2.0
mariadb                1.0.0
MarkupSafe             1.1.1
matplotlib             3.3.0
mcstatus               3.1.1
mouse                  0.7.1
MouseInfo              0.1.3
multidict              4.7.6
mysql-connector-python 8.0.21
numpy                  1.19.0
opencv-python          4.3.0.36
ovr                    1.16.1
Pillow                 7.2.0
pip                    20.1.1
praw                   7.1.0
prawcore               1.5.0
protobuf               3.12.2
PyAutoGUI              0.9.50
PyDirectInput          1.0.2
PyGetWindow            0.0.8
PyMsgBox               1.0.8
pyparsing              2.4.7
pyperclip              1.8.0
pypicoboard            0.0.0
pypresence             4.0.0
PyRect                 0.1.4
PyScreeze              0.1.26
python-dateutil        2.8.1
python-ovrsdk          0.3.2.2
PyTweening             1.0.3
pytz                   2020.1
pywin32                228
pywinauto              0.6.8
PyYAML                 5.3.1
requests               2.24.0
serial                 0.0.97
setuptools             47.1.0
six                    1.15.0
Snookey2               3.2.1
typing-extensions      3.7.4.2
tzlocal                2.1
update-checker         0.18.0
urllib3                1.25.9
websocket-client       0.57.0
websockets             8.1
Werkzeug               1.0.1
winput                 1.2.2
yarl                   1.5.0

**Comment by OskarZyg** [comment]
I was using the example code.

**Comment by drewarnett** [comment]
You have https://pypi.org/project/serial/ installed.  You need
https://pypi.org/project/pyserial/.

If you need the first one for other things, you'll need to do something to
deal with the namespace collision issue.  Let me know if you need help with
that.

Yes, I've done this before.

Looks like you're on windows with python 3.x, so python -m pip install
pyserial or py -3 -m pip install pyserial depending on whether you're using
python launcher for windows or not.  If you're using virtual environments,
handle that as you see fit.

Best regards,

Drew
